[package]
name = "app-store-server-library"
description = "The Rust server library for the App Store Server API and App Store Server Notifications"
version = "0.5.0"
repository = "https://github.com/namecare/app-store-server-library-rust"
homepage = "https://github.com/namecare/app-store-server-library-rust"
authors = ["tkhp", "namecare"]
license = "MIT"
readme = "README.md"
documentation = "https://docs.rs/app-store-server-library"
keywords = ["apple", "appstore"]
edition = "2021"

[dependencies]

x509-verify = { version = "0.4.5", features = ["x509"] }
# Cryptography
jwt-simple = "0.12.7"
pem = "3.0.2"

# Serialization
serde = { version = "1.0.188", features = ["derive"] }
serde_json = { version = "1.0.105" }
serde_with = { version = "3.3.0", features = ["chrono"] }
uuid = { version = "1.4.1", features = ["serde", "v4"] }
chrono = { version = "0.4.28", features = ["serde"] }
base64 = "0.21.3"

# Utils
thiserror = "1.0.47"

[dev-dependencies]
dotenv = "0.15.0"
